
version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: ./Docker/Dockerfile
    image: myapp
    container_name: myapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - /var/www/vendor
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network
  db:
    image: mysql
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - laravel-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
       - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: unless-stopped
    ports:
      - 8181:80
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
